version: "3"


services:


  backend:
    image: vladyalk/apartament-backend:latest


    environment:
      - DATABASE_URL=${DATABASE_URL}
      
    restart: unless-stopped
    ports:
      - "17000:8000"
